#!/usr/bin/env python3
"""
Demo: Visualization of CSV Export Feature

This script demonstrates what the CSV export feature produces
by showing example output formats.
"""

def print_demo():
    print("="*70)
    print("CSV Export Feature - Output Example")
    print("="*70)
    print()
    
    print("Command:")
    print("  python main_qm9.py \\")
    print("      --dataset ase_db \\")
    print("      --ase_db_path ase.db \\")
    print("      --export_conditions_csv ./output \\")
    print("      --no_wandb \\")
    print("      --remove_h")
    print()
    print("="*70)
    print()
    
    # 1. molecular_weight.csv
    print("1. molecular_weight.csv")
    print("-" * 70)
    print("ID,分子の組成,分子量")
    print("0,C6H12O6,180.1559")
    print("1,C8H10N4O2,194.1906")
    print("2,C9H8O4,180.1574")
    print("3,C2H6O,46.0684")
    print("...")
    print()
    print("Contains:")
    print("  - ID: Unique molecule identifier")
    print("  - 分子の組成: Molecular formula (e.g., C6H12O6 for glucose)")
    print("  - 分子量: Molecular weight in Daltons")
    print()
    
    # 2. pi_conjugation_ratio.csv
    print("2. pi_conjugation_ratio.csv")
    print("-" * 70)
    print("ID,分子の組成,π共役比率")
    print("0,C6H12O6,0.1667")
    print("1,C8H10N4O2,0.5556")
    print("2,C9H8O4,0.6667")
    print("3,C2H6O,0.0000")
    print("...")
    print()
    print("Contains:")
    print("  - ID: Unique molecule identifier")
    print("  - 分子の組成: Molecular formula")
    print("  - π共役比率: π-conjugation ratio (0.0 to 1.0)")
    print("    Higher values indicate more π-conjugated bonds")
    print()
    
    # 3. atom_types_encoding.csv
    print("3. atom_types_encoding.csv")
    print("-" * 70)
    print("ID,分子の組成,C,H,N,O,F,S,P,Cl")
    print("0,C6H12O6,1,1,0,1,0,0,0,0")
    print("1,C8H10N4O2,1,1,1,1,0,0,0,0")
    print("2,C9H8O4,1,1,0,1,0,0,0,0")
    print("3,C2H6O,1,1,0,1,0,0,0,0")
    print("...")
    print()
    print("Contains:")
    print("  - ID: Unique molecule identifier")
    print("  - 分子の組成: Molecular formula")
    print("  - Element columns (C, H, N, O, etc.): Binary encoding")
    print("    1 = element present, 0 = element absent")
    print()
    
    # 4. functional_groups_encoding.csv
    print("4. functional_groups_encoding.csv")
    print("-" * 70)
    print("ID,分子の組成,carbonyl,hydroxyl,amine,carboxyl,ester,ether")
    print("0,C6H12O6,1,1,0,0,0,1")
    print("1,C8H10N4O2,1,0,1,0,0,0")
    print("2,C9H8O4,1,1,0,1,0,1")
    print("3,C2H6O,0,1,0,0,0,0")
    print("...")
    print()
    print("Contains:")
    print("  - ID: Unique molecule identifier")
    print("  - 分子の組成: Molecular formula")
    print("  - Functional group columns: Binary encoding")
    print("    1 = functional group present, 0 = functional group absent")
    print()
    
    print("="*70)
    print("Key Features")
    print("="*70)
    print()
    print("✓ All molecules from train/valid/test splits combined")
    print("✓ Japanese column headers for intuitive understanding")
    print("✓ UTF-8 encoded CSV files compatible with Excel/LibreOffice")
    print("✓ Binary encodings for categorical features (atom types, functional groups)")
    print("✓ Molecular formulas for easy identification")
    print()
    
    print("="*70)
    print("Use Cases")
    print("="*70)
    print()
    print("1. Dataset Analysis:")
    print("   - Understand molecular diversity")
    print("   - Identify common functional groups")
    print("   - Analyze molecular weight distribution")
    print()
    print("2. Conditional Generation:")
    print("   - Select target conditions for generation")
    print("   - Prepare conditioning data")
    print("   - Verify generated molecules match conditions")
    print()
    print("3. Data Exploration:")
    print("   - Visualize property distributions")
    print("   - Find molecules with specific characteristics")
    print("   - Compare datasets")
    print()
    
    print("="*70)
    print("Example Analysis with Pandas")
    print("="*70)
    print()
    print("import pandas as pd")
    print("import matplotlib.pyplot as plt")
    print()
    print("# Load molecular weights")
    print("df = pd.read_csv('output/molecular_weight.csv')")
    print()
    print("# Show statistics")
    print("print(df['分子量'].describe())")
    print()
    print("# Plot distribution")
    print("df['分子量'].hist(bins=50)")
    print("plt.xlabel('Molecular Weight (Da)')")
    print("plt.ylabel('Frequency')")
    print("plt.title('Molecular Weight Distribution')")
    print("plt.show()")
    print()
    print("# Find molecules with specific weight range")
    print("target_molecules = df[(df['分子量'] >= 150) & (df['分子量'] <= 200)]")
    print("print(f'Found {len(target_molecules)} molecules in target range')")
    print()

if __name__ == '__main__':
    print_demo()
